name: pytest
on:
  # this has no filter, and will trigger on all branch
  # [push, workflow_dispatch]
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [opened]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: print github action context
        run: echo ${{ github.repositoryUrl }}
      - name: pre - checkout
        run: |
          pwd
          ls -lh
      # - name: clone repo
      #   run: |
      #     git clone  https://github.com/JornsenChao/python_github_action-demo
      #     cd python_github_action-demo
      - name: checkout code
        uses: actions/checkout@v4
      - name: after - checkout
        run: |
          pwd
          ls -lh
      - name: install pytest
        run: pip install pytest
      - name: run pytest
        run: pytest
