name: pytest
on:
  # this has no filter, and will trigger on all branch
  # [push, workflow_dispatch]
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [opened]
    # opened: a new user forked the main, do some edit, and create pull request; as a the maintainer of the main, i will manually approve this, then the new pull request will trigger this action (to prevent attack on running too many pull request on the main branch).
    # After i approve and this pass the action test, and i merge the pull request, this user will become contributor (from previously "first-time contributor")
    # And the next time this user create pull request from his own branch, the action will automatically run , without manual approve from me
  schedule:
    - cron: "*/5 * * * *"

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: print github action context
        run: echo ${{ github.repositoryUrl }}
      - name: pre - checkout
        run: |
          pwd
          ls -lh
      # - name: clone repo
      #   run: |
      #     git clone  https://github.com/JornsenChao/python_github_action-demo
      #     cd python_github_action-demo
      - name: checkout code
        uses: actions/checkout@v4
      - name: after - checkout
        run: |
          pwd
          ls -lh
      - name: install pytest
        run: pip install pytest
      - name: run pytest
        run: pytest
